theme: jekyll-theme-minimal
title: Rui Pires
description: >
  <br>
  <b>Summary</b><br>
  <ul>
  <li>Lead of Accenture Artificial Intelligence team in Braga.</li>
  <li>8+ years of Software Development</li>
  <li>Cloud and DevOps Solution Architect.</li>
  </ul>
  <br>
  <b>Contacts</b><br>
  <b>email</b><a href="mailto:ruipiresc@gmail.com">ruipiresc@gmail.com</a><br>
author: Rui Pires
# author-img: ruipiresc.jpg pending upload
about-author: Born in 1993, Portugal. Master degree in Electrical and Computer Engineering. Leading Accenture Artificial Intelligence team in Braga.
social-twitter: ruipiresc
social-facebook: ruipiresc
social-github: ruipiresc
social-linkedin: ruipiresc
social-email: ruipiresc@gmail.com
