theme: jekyll-theme-minimal
title: Rui Pires
description: >
  <br>
  <b>Summary</b><br>
  ➕ Lead of Accenture Artificial Intelligence team in Braga.<br>
  ➕ 8+ years of Software Development<br>
  ➕ Cloud and DevOps Solution Architect.<br>
  <br>
  <br>
  <b>Skills</b><br>
  ➕ python<br>
  ➕ typescript<br>
  ➕ SQL<br>
  ➕ AI and ML<br>
  ➕ DevOps<br>
  ➕ Cloud<br>
  ➕ Docker<br>
  <br>
  <br>
  <b>Languages</b><br>
  ➕ Native Portuguese<br>
  ➕ Fluent English<br>
  ➕ Intermediate Spanish<br>
  <br>
  <br>
  <b>Education</b><br>
  🎓 University of Coimbra<br>
  💠 Electrical and Computer Engineering<br>
  October 2011 - September 2016<br>
  ➕ Bachelor's degree, 2014<br>
  ➕ Master's degree, Robotics, 2016<br>
  <br>
  <br>
  <b>Contacts</b><br>
  <a href="mailto:ruipiresc@gmail.com">📧 ruipiresc@gmail.com</a><br>
  <a href="https://www.linkedin.com/in/ruipiresc/">LinkedIn🔗 ruipiresc</a><br>
author: Rui Pires
# author-img: ruipiresc.jpg pending upload
about-author: Born in 1993, Portugal. Master degree in Electrical and Computer Engineering. Leading Accenture Artificial Intelligence team in Braga.
social-twitter: ruipiresc
social-facebook: ruipiresc
social-github: ruipiresc
social-linkedin: ruipiresc
social-email: ruipiresc@gmail.com
